### ISSUE TITLE
tag release?

### ISSUE THREAD

**Issue by druvus** [dayzerodx/counterr#1]
Would it possible to get a tag 0.1 release? I was thinking of adding the tool to Bioconda. See open PR  bioconda/bioconda-recipes#12541

**Comment by epruesse** [comment]
FYI: Github can do tags via the web interface. You can just go to https://github.com/dayzerodx/counterr/releases/new, enter `0.1` and click publish. It'll tag the most recent commit in the selected branch and create the zip/tar.gz files for download.

**Comment by jaekor91** [comment]
@druvus I just tagged the latest commit as v0.1 following @epruesse's instruction. Thank you for using counterr.

**Comment by druvus** [comment]
@jaekor91 thanks!
