### ISSUE TITLE
Extracting raw data from outputs

### ISSUE THREAD

**Issue by ziels** [dayzerodx/counterr#3]
Hi, I am wondering if there is a way to retrieve the raw data from the output of counterr? For instance, is there a way to retrieve the data that goes into the dist_len_hp.pdf and dist_indel_**.pdf plots? 

Thanks! 
Ryan

**Comment by jaekor91** [comment]
Hi Ryan -- Thanks for the question! I updated README.md to include additional documentation for files under the "stats" subdirectory of the output directory. Please let me know if that was clear enough for your purpose.
